---
- name: Update AD user attribute employeeType
  hosts: ad_servers
  gather_facts: no

  collections:
    - ansible.windows
    - community.windows

  vars:
    ad_username: "G538164"
    ad_employeeType: "Ansible"

  tasks:
    - name: Update EmployeeType Attribute
      win_shell: |
        Import-Module ActiveDirectory
        Set-ADUser -Identity "{{ ad_username }}" -Replace @{employeeType="{{ ad_employeeType }}"}



