---
- name: Update AD user attribute employeeType
  hosts: ad_servers
  gather_facts: no

  collections:
    - ansible.windows
    - community.windows

  vars:
    ad_username: "G538164"
    ad_employeeType: "Ansible"

- name: Ensure necessary python packages are installed for the correct interpreter    
    ansible.builtin.pip:    
      name:    
          - Install pywinrm
  delegate_to: localhost

  tasks:
    - name: Update EmployeeType Attribute
      win_shell: |
        Import-Module ActiveDirectory
        Get-ADUser -Identity G538164
        # Set-ADUser -Identity "{{ ad_username }}" -Replace @{employeeType="{{ ad_employeeType }}"}



