---
  collections:
  - name: ansible.windows
  - name: community.windows
- name: Update AD user Attribute employeeType
  hosts: ad_servers
  gather_facts : no

  vars:
    ad_username : "G538164"
    ad_employeeType : "Ansible"

  tasks:

    - name : Update EmployeeType Attribute
      win_shell:
        Import-Module Active Directory
        Set-Aduser -Identity "{{ad_username}}" -Replace @{employeeType ="{{ad_employeeType}}"}
      register : Update_result
